# Generated by Django 4.1.5 on 2023-01-23 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='descripton',
            new_name='description',
        ),
    ]
