# Generated by Django 4.1.4 on 2023-01-26 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_category_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
